#:schema node_modules/wrangler/config-schema.json
name = "monad-blitz-medellin"
compatibility_date = "2026-06-06"

[build]
command = "npm install --prefix monadRoad && npm run build --prefix monadRoad"

[assets]
directory = "./monadRoad/dist"
